import Head from 'next/head';
import { useState, useRef } from 'react';

import CloseIcon from '@mui/icons-material/Close';
import SearchIcon from '@mui/icons-material/Search';

import heroImage from '../Images/hero1.jpg';
import heroImage2 from '../Images/hero2.jpg';
import heroImage3 from '../Images/hero3.jpg';
import secondImage from '../Images/second.jpg';
import destinationsIcon from '../Images/Icons/destinations.svg';
import discountIcon from '../Images/Icons/discount.svg';
import earthIcon from '../Images/Icons/earth.svg';
import holidayIcon from '../Images/Icons/holiday.svg';
import hotelIcon from '../Images/Icons/hotel.svg';
import ticketIcon from '../Images/Icons/ticket.svg';
import gridImage1 from '../Images/forth1.jpg';
import gridImage2 from '../Images/forth2.jpg';
import gridImage3 from '../Images/forth3.jpg';
import gridImage4 from '../Images/forth4.jpg';
import gridImage5 from '../Images/forth5.jpg';

import Dots from '../Components/Dots';
import Slide from '../Components/Slide';

export default function Home() {
  const [openMenu, setOpenMenu] = useState(false);

  return (
    <div>
      <Head>
        <title>TRVL - Travel Across The World</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Header */}
      <div className='py-6 lg:bg-green relative'>
        <div className='lg:hidden bg-green absolute w-1/2 h-full top-0'></div>
        <div className='absolute h-[310px] w-[340px] top-[0px] right-0 bg-orange lg:hidden'>
          <div className='absolute bottom-[-35px] right-[40px]'>
            <Dots bgColor='bg-green' />
          </div>
        </div>
        <div className='flex justify-between w-10/12 mx-auto items-center lg:w-11/12'>
          <div className='playfair text-orange text-2xl relative'>TRVL</div>
          <div
            className={`flex items-center relative lg:fixed lg:bg-green lg:h-screen lg:top-0 lg:w-full lg:z-20 lg:flex-col lg:items-start lg:justify-between lg:p-6 transition-all ease-in duration-75 ${
              openMenu ? 'lg:left-0' : 'lg:left-full'
            }`}
          >
            <div className='hidden lg:flex lg:justify-between lg:w-full lg:items-center'>
              <div className='playfair text-orange text-2xl'>TRVL</div>
              <div onClick={() => setOpenMenu(false)}>
                <CloseIcon className='!fill-orange' />
              </div>
            </div>
            <p className='cursor-pointer   text-sm font-medium mx-8 lg:mx-0 lg:my-8 lg:text-white lg:text-xl'>
              Home
            </p>
            <p className='cursor-pointer   text-sm font-medium mx-8 lg:mx-0 lg:my-8 lg:text-white lg:text-xl'>
              About
            </p>
            <p className='cursor-pointer   text-sm font-medium mx-8 lg:mx-0 lg:my-8 lg:text-white lg:text-xl'>
              Destinations
            </p>
            <p className='cursor-pointer   text-sm font-medium mx-8 lg:mx-0 lg:my-8 lg:text-white lg:text-xl'>
              Contact
            </p>
            <div className='cursor-pointer text-sm font-medium  py-3 px-6 rounded bg-green text-orange lg:bg-orange lg:text-green lg:font-bold'>
              BOOK NOW
            </div>
          </div>
          <div
            className='hidden h-[15px] lg:flex lg:items-end lg:flex-col lg:justify-between cursor-pointer'
            onClick={() => setOpenMenu(true)}
          >
            <div className='w-[25px] h-[2px] bg-orange'></div>
            <div className='w-[16px] h-[2px] bg-orange'></div>
          </div>
        </div>
      </div>

      {/* Hero */}
      <div className='relative'>
        <div className='flex'>
          <div className='flex w-1/2 lg:absolute lg:w-full lg:h-full'>
            <div className='bg-green h-full flex items-end justify-center lg:hidden w-[100px] pb-[330px]'>
              <div className='rotate-[-90deg] flex text-white items-center'>
                <div className='mx-5 cursor-pointer'>Instagram</div>
                <div className='mx-5 cursor-pointer'>Facebook</div>
                <div className='mx-5 cursor-pointer'>Twitter</div>
                <div className='w-[250px] h-[1px] bg-white'></div>
              </div>
            </div>
            <div className='relative after:absolute after:h-full after:w-full after:bg-overlay z-10 after:top-0 left-0 lg:w-full'>
              <img className='w-full h-full' src={heroImage.src} />
            </div>
          </div>
          <div className='flex-1 flex flex-col lg:flex-row relative z-10 sm:flex-col'>
            <div className='flex-1 w-4/5 pl-10 pt-10 mb-24 lg:mb-10 lg:pr-6 md:pl-5 md:pr-5 sm:mb-10 sm:w-full sm:p-2 sm:py-10'>
              <h1 className='playfair text-5xl leading-relaxed tracking-wide font-bold lg:text-orange md:text-4xl'>
                It's Your Time To <br /> See The World
              </h1>
              <p className='par my-12'>
                Magna etiam tempor orci eu lobortis elementum nibh. Diam quis
                enim lobortis scelerisque fermentum dui faucibus in ornare.
              </p>
              <form
                onSubmit={(e) => e.preventDefault()}
                className='flex w-full justify-between  shadow-current shadow-slate-300 p-2 pl-5 rounded bg-white md:p-2'
              >
                <div>
                  <div className='font-semibold mb-3 sm:text-sm'>From</div>
                  <div className='text-gray-400 md:text-sm sm:text-xs'>
                    Serbia
                  </div>
                </div>
                <div>
                  <div className='font-semibold mb-3 sm:text-sm'>To</div>
                  <div className='text-gray-400 md:text-sm sm:text-xs'>
                    Croatia
                  </div>
                </div>
                <div>
                  <div className='font-semibold mb-3 sm:text-sm'>When</div>
                  <div className='text-gray-400 md:text-sm sm:text-xs'>
                    July
                  </div>
                </div>
                <div>
                  <div className='font-semibold mb-3 sm:text-sm'>
                    Travel Type
                  </div>
                  <div className='text-gray-400 md:text-sm sm:text-xs'>
                    Solo
                  </div>
                </div>
                <button className='bg-green px-4 rounded'>
                  <SearchIcon className='!fill-orange' />
                </button>
              </form>
            </div>
            <div className='flex h-[170px] lg:flex-col lg:h-full lg:w-[280px] md:w-[200px] sm:flex-row sm:w-full'>
              <div className='lg:flex-1'>
                <img className='h-full w-[800px]' src={heroImage2.src} />
              </div>
              <div className='lg:flex-1'>
                <img className='h-full w-[800px]' src={heroImage3.src} />
              </div>
              <div className='playfair flex items-center justify-center cursor-pointer text-green bg-orange w-full font-semibold text-xl lg:flex-1 text-center sm:text-base'>
                Find Out More
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* 2 Section */}
      <div className='relative my-52 sm:my-40'>
        <div className='w-[550px] h-[450px] bg-green absolute top-[-100px] left-[-100px] hidden 2xl:block 2xl:left-0 lg:hidden'></div>
        <div className='flex narrow-div xl:items-center lg:flex-col-reverse lg:items-start'>
          <div className='relative flex-1 flex justify-end pr-20 md:w-3/5 sm:w-full'>
            <div className='w-[550px] h-[450px] bg-green absolute top-[-100px] left-[-100px] 2xl:hidden'></div>
            <div className='absolute rounded-full h-[100px] w-[100px] bg-transparent border-4 border-orange top-[-30px] left-[50px] 2xl:hidden'></div>
            <div className='relative'>
              <img className='w-[650px]' src={secondImage.src} />
            </div>
            <div className='absolute bottom-[-35px] right-[20px]'>
              <Dots bgColor='bg-orange' />
            </div>
          </div>
          <div className='flex-1 lg:mb-10'>
            <h1 className='playfair title'>
              There Are Several Reasons To Relax Next To Us
            </h1>
            <p className='par mt-3 mb-14'>
              Nisl condimentum id venenatis a condimentum vitae sapien. Nulla at
              volutpat diam ut venenatis tellus in metus vulputate.
            </p>
            <div className='flex lg:mb-14'>
              <div className='mr-20 sm:mr-10'>
                <div className='flex items-center'>
                  <img className='w-[40px] mr-3' src={destinationsIcon.src} />
                  <p className='font-semibold text-sm sm:text-xs'>
                    Amazing Destinations
                  </p>
                </div>
                <div className='flex items-center my-5'>
                  <img className='w-[40px] mr-3' src={ticketIcon.src} />
                  <p className='font-semibold text-sm sm:text-xs'>
                    The Best Airline Offers
                  </p>
                </div>
                <div className='flex items-center'>
                  <img className='w-[40px] mr-3' src={hotelIcon.src} />
                  <p className='font-semibold text-sm sm:text-xs'>
                    The Best Hotel Offers
                  </p>
                </div>
              </div>
              <div>
                <div className='flex items-center'>
                  <img className='w-[40px] mr-3' src={discountIcon.src} />
                  <p className='font-semibold text-sm sm:text-xs'>
                    Often Special Deals
                  </p>
                </div>
                <div className='flex my-5 items-center'>
                  <img className='w-[40px] mr-3' src={earthIcon.src} />
                  <p className='font-semibold text-sm sm:text-xs'>
                    World Wide Connection
                  </p>
                </div>
                <div className='flex items-center'>
                  <img className='w-[40px] mr-3' src={holidayIcon.src} />
                  <p className='font-semibold text-sm sm:text-xs'>
                    Holiday Offers
                  </p>
                </div>
              </div>
            </div>
            <div className='mt-10'>
              <button className='bg-green font-semibold py-3 px-9 text-orange'>
                See More
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* 3rd Section */}
      <div className='relative py-10 my-52 sm:my-40'>
        <div className='w-2/5 absolute left-0 top-0 h-full bg-green lg:w-1/2 xs:w-full'></div>
        <div className='narrow-div'>
          <div className='relative mb-5'>
            <div className='playfair title text-orange'>
              Discover Some Of Our Destinations
            </div>
            <div className='flex justify-end'>
              <p className='inline-block cursor-pointer text-green font-semibold xs:text-lg-text'>
                Explore More
              </p>
            </div>
          </div>
          <div>
            <Slide />
          </div>
        </div>
      </div>

      {/* 4th Section */}
      <div className='relative  my-52 sm:my-40'>
        <div className='h-full w-2/5 bg-orange absolute left-0 top-0 md:w-1/2'></div>
        <div className='narrow-div flex items-center lg:flex-col'>
          <div className='flex-1 relative lg:my-10 md:px-5'>
            <h1 className='playfair title'>
              The Place Where You Can Schedule Your Enjoyment
            </h1>
            <p className='par mt-3'>
              Nisl condimentum id venenatis a condimentum vitae sapien. Nulla at
              volutpat diam.
            </p>
            <div className='flex items-end my-10'>
              <div className='mr-10'>
                <div className='font-semibold text-lg'>More than</div>
                <div className='text-green font-bold text-4xl'>12K</div>
                <div className='font-semibold text-lg'>Happy Customers</div>
              </div>
              <div>
                <div className='text-green font-bold text-4xl'>11</div>
                <div className='font-semibold text-lg'>Years in Bussines</div>
              </div>
            </div>
            <button className='bg-green font-semibold py-3 px-9 text-orange'>
              See More
            </button>
          </div>
          <div className='w-[600px] relative xl:w-[500px] lg:hidden'>
            <div className='relative z-10'>
              <div className='flex mb-[2px]'>
                <img
                  className='h-[180px] w-[180px] mr-[2px] xl:h-[130px] xl:w-[110px]'
                  src={gridImage1.src}
                />
                <img
                  className='h-[180px] xl:h-[130px] flex-1'
                  src={gridImage4.src}
                />
              </div>
              <div className='flex mb-[2px]'>
                <img
                  className='h-[180px] xl:w-[200px] flex-1 mr-[2px]'
                  src={gridImage3.src}
                />
                <img className='h-[180px] xl:w-[200px]' src={gridImage5.src} />
              </div>
              <div>
                <img className='h-[250px] w-full' src={gridImage2.src} />
              </div>
            </div>
            <div className='absolute bottom-[-50px] right-[-30px]'>
              <Dots bgColor='bg-green' />
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className='bg-green py-14 text-white'>
        <div className='narrow-div flex justify-between sm:flex-col'>
          <div className='playfair text-orange text-2xl relative sm:mb-10'>
            TRVL
          </div>
          <div className='sm:mb-10'>
            <h3 className='font-semibold mb-5 text-lg'>Contact</h3>
            <p className='my-3 font-light cursor-pointer'>Instargram</p>
            <p className='my-3 font-light cursor-pointer'>Linkedin</p>
            <p className='my-3 font-light cursor-pointer'>Facebook</p>
            <p className='my-3 font-light cursor-pointer'>Twitter</p>
          </div>
          <div className='sm:mb-10'>
            <h3 className='font-semibold mb-5 text-lg'>Useful links</h3>
            <p className='my-3 font-light cursor-pointer'>Home</p>
            <p className='my-3 font-light cursor-pointer'>About</p>
            <p className='my-3 font-light cursor-pointer'>Destinations</p>
            <p className='my-3 font-light cursor-pointer'>Contact</p>
          </div>
          <div className='sm:mb-10'>
            <h3 className='font-semibold mb-5 text-lg'>Support</h3>
            <p className='my-3 font-light cursor-pointer'>
              Affiliate Marketing
            </p>
          </div>
          <div className='sm:mb-10'>
            <h3 className='font-semibold mb-5 text-lg'>Help Us</h3>
            <p className='my-3 font-light cursor-pointer'>Report a problem</p>
          </div>
        </div>
      </div>
    </div>
  );
}
